### ISSUE TITLE
Add currency tracking (at least for raid/dungeon-based currencies)

### ISSUE THREAD

**Issue by SacredDuckwhale** [chancedj/LockedOut#10]
Similar to SavedInstances, tracking currencies across characters has been requested [here](https://mods.curse.com/addons/wow/274882-lockedout?comment=2).

It makes sense to at least have bonus rolls and similar currencies being tracked - which, more accurately, means tracking their lockout/weekly quests and not just the amount where necessary.

Going from there, other currencies could be tracked in a similar way, but I'll have to look into SI's functionality some more to understand what exactly people might be looking for here.

Basic roadmap (subject to change):
- [x] Add basic currency tracking
- [x] Add bonus roll (weekly quest) tracking
- [x] Update display to show currencies as well
- [x] Provide some sort of options to allow users to select which currencies should be displayed

The latter would obviously make sense for the raid lockouts, as well, but that's a different issue :P

**Comment by chancedj** [comment]
these links should be helpful when implementing this later.

https://wow.gamepedia.com/API_GetCurrencyListInfo
https://wow.gamepedia.com/API_GetCurrencyListSize

**Comment by Daeveren** [comment]
Here's how i had setup SI. For me, showing the currencies is a must have and actually more important than the dungeon/raid tracking (but is best seeing them in the same tooltip anyway). Please consider adding more, eventually covering all the currencies SI had. 
![2017-08-31 23_25_15-world of warcraft](https://user-images.githubusercontent.com/6321337/29943854-c9587ce6-8ea3-11e7-9d26-b82e8e9ef3af.jpg)

**Comment by chancedj** [comment]
Thanks for the feedback.  I haven't setup what feature i'm adding for 1.4.0 - but it might just be that i go ahead and tackle both this and another minor (tooltips for boss data) to that release.

I appreciate the feedback from people letting me know what features they find most frustrating that are missing as it helps to give me a priority on what i can move to next.

**Comment by SacredDuckwhale** [comment]
If you're doing the tooltip, this was the screenshot I made after a user asked for the feature: [imgur link](http://imgur.com/r6fFysE) - It could serve as orientation.

I was busy and so I forgot to add it as a separate issue here :)

**Comment by chancedj** [comment]
great, that's pretty much what i'm looking to do - so works for me :).

**Comment by chancedj** [comment]
new branch has rudimentary support for currency.  i need to investigate the weekly quests to get the coins and see how that ties into the counts available.  SI uses a reset counter, but i think it would be better to use the proper quest api's.

I also do not display just current expansion data.  however i'm not sure that i'll exclude that data as it might be best to go with what the user is watching and has flagged as unused in the currency tab of the player.  At least until release 1.5 where i finally get around to adding config options.

You're welcome to give feedback on what i currently have - just know it's about 30 minutes of work and still needs quite a bit of work - so not even close to release atm :)....maybe alpha (as far as features).

**Comment by SacredDuckwhale** [comment]
Looks like a good start so far! I'd add some formatting (colours and grouping), ideally categorize the world bosses and currencies according to expansions or any other criteria that can easily be implemented. More nuanced options could be added later with a config GUI.

Here's an old screenshot of how I wanted to configure SI (but it didn't offer that functionality, either): [imgur link](http://imgur.com/vKPP05m) - grouped by colour to have headlines like those pictured in the screenshot provided by Daeveren, except for currencies and bosses and not just raids.

**Comment by chancedj** [comment]
all 4 items are done.  download it and check it out if you'd like.  closed out a few other items so that all that are left are the 2 issues with data showing on hover. 

It doesn't break everything down by expansion yet - and if there are weekly quests for the old expansion bonus rolls i would need to implement those as well.  Let me know if you have the quest id that goes with the names and i'll implement those.

**Comment by SacredDuckwhale** [comment]
The currencies seem to be tracked just fine :)  But I think what people meant with "bonus roll tracking" was to track the weekly quest, not the currency itself - right now, it shows "Seal of Broken Fate: 4/6" (which is true in terms of currencies), when the interesting info would be 0/3 (I haven't purchased/obtained any this week)... if you know what I mean?

Edit: Nevermind, I checked out the wrong branch. I'm really not used to release branches >_>

I can't find any options to configure what currencies should be displayed - if that is implemented then I guess I can close the issue (you can do it, too) as the rest would be refining the display and adding more options over time.

**Comment by chancedj** [comment]
if you go to the currency tab on your character profile, click on the currencies there.  if you don't want to have one show then click on the unused box and it won't show up as tracked in my addon.  i'm going to add another issue to - if you click on the currency - it will open that screen so hopefully people will know to go there and i won't have to duplicate the effort that blizzard already has :).

**Comment by Daeveren** [comment]
Well, SI was/is doing it completely different. For one, in terms of displaying it, it is displaying both the total seals and the weekly seal status, check the pic

![2017-09-04 23_25_00-world of warcraft](https://user-images.githubusercontent.com/6321337/30037940-6f868a78-91c8-11e7-8310-b11bdd5fd17f.jpg)

Then, the implementation via tracked currencies "show on bags" via default UI is conflicting with the bags addons! For example, I use Bagnon (the most popular bag addon for wow) and I can display 1-2 currencies there right at the bottom-left of my bag (setting it to 3 or more won't have enough display area there)

![2017-09-04 23_27_17-world of warcraft](https://user-images.githubusercontent.com/6321337/30037968-b56141a0-91c8-11e7-9842-14bf0c73ae8d.jpg)

The way SI was doing is preferable, since it offer a way greater flexibility there. In the above screenshot (#1) I display 9 different currencies there, plus the bonus roll (which is not a currency). Setting it to 9 currencies will screw up anyone that uses Bagnon.

**Comment by chancedj** [comment]
So you're saying it's preferable that I implement something else to all the user to track currencies as opposed to making them use the unused box?

I may have to delay 1.4 and go ahead and push the config settings from 1.5 to 1.4 and make this an all inclusive release...

**Comment by chancedj** [comment]
*to allow the user.  Stupid phone!

**Comment by Daeveren** [comment]
Well, in my opinion, SI was doing it in a great way with having them in the addon settings. I can see why using the default "show on bags" would have other advantages (like being future proof?), but it'll screw up with Bagnon users. I might leave with it like this, but since Bagnon is the most popular bag addon, I guess other players will have an issue /conflict with this.

**Comment by chancedj** [comment]
Ok thanks.  Then what I may end up doing is just giving the user an option if I feel like getting fancy.  Otherwise I'll just stick to letting them pick what they want to see.

I'll split the weekly dalaran quests vs broken shore quests for the weekly instead of combining them.  So that it is (3/3) instead of (6) when all are complete

**Comment by SacredDuckwhale** [comment]
I believe that the "Show on bags" setting isn't used, but the "Unused" setting is considered to hide currencies. That is, all currencies are displayed initally (no need to set them manually via "Show on bags"), but when you mark it as unused, it will be hidden for that character.

Flexibility issues aside, I think setting the currencies indepently of the default currency frame is preferable. Currencies could be set globally (as opposed to checking the same "Unused" boxes on all characters) as well as individually without interfering with any other addon or default UI setting.

**Comment by Daeveren** [comment]
Ah yes, good point there - while the "Unused" thingie looks good (as in, not interfering with other addons, atleast none that I use lol), it would be problematic in the way that you would have to log on each of your alts and set it with exactly the same currencies for each of them. A global setting (in the addon options) would be the a more elegant way to handle this, I suppose. So like, if you want to disable displaying the Darkmoon Tickets, you will just uncheck it in addon's setting, as opposed to logging on all your 12 alts and check the "unused" thing on each of them.
