### ISSUE TITLE
Add tracking of various lockout-based features

### ISSUE THREAD

**Issue by SacredDuckwhale** [chancedj/LockedOut#12]
Since it has been requested on Curse, I'll just list the missing features that would (sort of) fit the scope of the addon but may require a lot of unrelated work to be finished first.

- [x] Add tracking for tradeskill cooldowns (daily and weekly?)
- [x] Add tracking for world bosses (world quests and otherwise?) - Maybe split this to make it easier
- [x] Add tracking of emissary quests - not really a lockout, but should be easy enough to include
- [x] Add class hall tracking quests
- [x] Add blingtron tracking

It's probably not going to happen overnight, but at the very least these requests should be taken into consideration when developing the architecture and data structures IF they are to be included at all... eventually, that is.

**Comment by chancedj** [comment]
Another one that, once we get it in ( #14 ) would be useful to probably follow suit.  just taking the issue so anyone picking this one up knows that the groundwork for menu options should probably be started.

**Comment by Daeveren** [comment]
Maybe consider tracking the daily free world quest (for the various classes that have such a perk in their class halls) but not as currency or daily quest. Also same for the Blingtron gift. Although probably both of them technically count as completed quests, I don't believe it would make sense to add them in the quests field in the LO list, but maybe threat them separately. As in: a separate entry "Blingtron" and showing either 'not opened' (with red text), or 'opened' (with green text) so one can see at a glance if he opened the gift that day (it's account wide). Similarly, for the classes that have the perk of completing a world quest for free, show the glanceable information if completed or not (the important part would be seeing when you have not completed it for this one, unlike say raid lockouts where you only need to show it up when you're saved).

**Comment by chancedj** [comment]
ok, thanks.  Added to the list.

**Comment by Daeveren** [comment]
Hehe, thanks. By Christmas you'll probably have 200 suggestions to implement :)
Well, technically, the 2 things proposed above fall in different categories, as follows: the free world quest thingie falls under "Legion only" stuff, since this is only available in the class halls (obviously we have no clue if next expansion Blizzard is going to do something similar). While the Blingtron thingie falls under a 'permanent' setting, in the way that each expansion has a newer/different version of Blingtron that needs to be tracked (but still only one Blingtron per account per day).

**Comment by chancedj** [comment]
going to have to start sticking help wanted on some of these issues eventually if it gets to that point....haha.

blingtron and class hall quest tracking may end up making it into 1.4.  if not, i'll likely try and put it into 1.5.  In the beginning i was looking to keep minor release versions 1.x.0 to 1 big feature....but there's more and more downloads and more requests - so going to take a little longer on the dev cycle, but add more features.

**Comment by Alyred** [comment]
For cooldown based features, what about profession cooldowns?  Jewelcrafting gem cutting WQ in Dalaran, Alchemist transmute, etc?
Additionally, any thoughts about the treasure room quest on the broken shore? Every 3 days, and while Nethershards aren't that valuable anymore, the bonus gold and order hall resources are still worth getting.

**Comment by chancedj** [comment]
ok, added to the list :).  we should really probably close this and break it down into seperate issues...thoughts?

**Comment by Daeveren** [comment]
Yes, it should be way easier to discuss when each entry in the list has its own page.

**Comment by chancedj** [comment]
closing.  the 3 that were open are now new issues opened separately as #44, #45, #46
